<#
.SYNOPSIS
Launches one ephemeral Fargate task from the stack's task definition, points
frontend/.env.local at its public IP, waits for the lifespan, then stops
that task (and only that task) — including on Ctrl+C or errors.

.DESCRIPTION
Replaces the old backend/run_ephemeral_cloud.ps1. Cluster, task definition,
subnet, and security group all come from the CloudFormation stack outputs —
nothing is passed by hand.

.EXAMPLE
.\run-dev-task.ps1 -LifespanMinutes 20
#>
param(
    [string]$StackName = "justateit-dev",
    [string]$AwsRegion = "us-east-2",
    [int]$LifespanMinutes = 15
)

$ErrorActionPreference = "Stop"

function Get-StackOutput([string]$Key) {
    $value = aws cloudformation describe-stacks `
        --region $AwsRegion `
        --stack-name $StackName `
        --query "Stacks[0].Outputs[?OutputKey=='$Key'].OutputValue" `
        --output text
    if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($value) -or $value -eq "None") {
        throw "Missing stack output '$Key'. Run deploy-stack.ps1 first."
    }
    return $value.Trim()
}

$Cluster = Get-StackOutput "ClusterName"
$TaskDefinition = Get-StackOutput "TaskDefinitionArn"
$SubnetId = Get-StackOutput "PublicSubnetId"
$SecurityGroupId = Get-StackOutput "TaskSecurityGroupId"

Write-Host "Launching one Fargate task ($LifespanMinutes min lifespan)..." -ForegroundColor Cyan
$RunResult = aws ecs run-task `
    --region $AwsRegion `
    --cluster $Cluster `
    --task-definition $TaskDefinition `
    --launch-type FARGATE `
    --count 1 `
    --network-configuration "awsvpcConfiguration={subnets=[$SubnetId],securityGroups=[$SecurityGroupId],assignPublicIp=ENABLED}" `
    | ConvertFrom-Json

if ($RunResult.failures) { throw "run-task failed: $($RunResult.failures | ConvertTo-Json -Compress)" }
$TaskArn = $RunResult.tasks[0].taskArn
if (-not $TaskArn) { throw "run-task returned no task ARN." }
Write-Host "Task: $TaskArn"

try {
    # ── Find the task's public IP (poll: task -> ENI -> association) ──
    $PublicIp = $null
    for ($attempt = 1; $attempt -le 24; $attempt++) {
        Start-Sleep -Seconds 5

        $Task = (aws ecs describe-tasks --region $AwsRegion --cluster $Cluster --tasks $TaskArn `
            | ConvertFrom-Json).tasks[0]

        if ($Task.lastStatus -eq "STOPPED") {
            throw "Task stopped during startup. Reason: $($Task.stoppedReason) " +
                  "(check CloudWatch log group from the stack outputs)"
        }

        $EniId = $Task.attachments[0].details |
            Where-Object { $_.name -eq "networkInterfaceId" } |
            Select-Object -ExpandProperty value -ErrorAction SilentlyContinue

        if ($EniId) {
            $Enis = (aws ec2 describe-network-interfaces --region $AwsRegion `
                --network-interface-ids $EniId | ConvertFrom-Json).NetworkInterfaces
            if ($Enis -is [array]) { $Enis = $Enis[0] }
            if ($Enis.Association.PublicIp) {
                $PublicIp = $Enis.Association.PublicIp
                break
            }
        }
    }
    if (-not $PublicIp) { throw "Timed out waiting for a public IP." }

    $ApiUrl = "http://${PublicIp}:8000"
    Write-Host "Backend is reachable at $ApiUrl (from the allowed CIDR only)" -ForegroundColor Green

    # ── Point the frontend at it via frontend/.env.local (gitignored;
    #    Expo loads it on top of .env) ──
    $RepoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
    $EnvLocal = Join-Path $RepoRoot "frontend\.env.local"
    @(
        "# Generated by infra/scripts/run-dev-task.ps1 — do not commit.",
        "EXPO_PUBLIC_API_URL=$ApiUrl",
        "EXPO_PUBLIC_FLAVOR_API_URL=$ApiUrl"
    ) | Set-Content -Path $EnvLocal
    Write-Host "Wrote $EnvLocal" -ForegroundColor Green
    Write-Host "Start the app with: cd frontend; npx expo start" -ForegroundColor Yellow

    # ── Wait out the lifespan (Ctrl+C stops the task early via finally) ──
    for ($remaining = $LifespanMinutes; $remaining -gt 0; $remaining--) {
        Write-Host "$remaining minute(s) remaining before the task is stopped..."
        Start-Sleep -Seconds 60
    }
    Write-Host "Lifespan reached." -ForegroundColor Yellow
}
finally {
    # Stop exactly the task we started — nothing else in the cluster.
    Write-Host "Stopping task $TaskArn..." -ForegroundColor Red
    aws ecs stop-task --region $AwsRegion --cluster $Cluster --task $TaskArn | Out-Null
    Write-Host "Task stopped. Fargate billing for it has ended." -ForegroundColor Green
}
